### ISSUE TITLE
Problem installing with Windows&conda

### ISSUE THREAD

**Issue by d-krupke** [CG-SHOP/pyutils23#24]
Here is the  error message we received by  mail:
```
Running command pip subprocess to install build dependencies
  Collecting conan
    Using cached conan-1.54.0-py3-none-any.whl
  Collecting setuptools
    Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
  Collecting scikit-build>=0.13
    Using cached scikit_build-0.16.2-py3-none-any.whl (78 kB)
  Collecting cmake>=3.17
    Using cached cmake-3.25.0-py2.py3-none-win_amd64.whl (32.6 MB)
  Collecting ninja
    Using cached ninja-1.11.1-py2.py3-none-win_amd64.whl (313 kB)
  Collecting requests<3.0.0,>=2.25
    Using cached requests-2.28.1-py3-none-any.whl (62 kB)
  Collecting pluginbase>=0.5
    Using cached pluginbase-1.0.1-py3-none-any.whl
  Collecting Jinja2<4.0.0,>=3.0
    Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
  Collecting PyYAML<=6.0,>=3.11
    Using cached PyYAML-6.0-cp38-cp38-win_amd64.whl (155 kB)
  Collecting six<=1.16.0,>=1.10.0
    Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
  Collecting bottle<0.13,>=0.12.8
    Using cached bottle-0.12.23-py3-none-any.whl (90 kB)
  Collecting PyJWT<3.0.0,>=2.4.0
    Using cached PyJWT-2.6.0-py3-none-any.whl (20 kB)
  Collecting tqdm<5,>=4.28.1
    Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
  Collecting fasteners>=0.14.1
    Using cached fasteners-0.18-py3-none-any.whl (18 kB)
  Collecting colorama<0.5.0,>=0.3.3
    Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
  Collecting node-semver==0.6.1
    Using cached node_semver-0.6.1-py3-none-any.whl (10 kB)
  Collecting patch-ng<1.18,>=1.17.4
    Using cached patch_ng-1.17.4-py3-none-any.whl
  Collecting urllib3<1.27,>=1.26.6
    Using cached urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
  Collecting pygments<3.0,>=2.0
    Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
  Collecting python-dateutil<3,>=2.7.0
    Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
  Collecting packaging
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting wheel>=0.32.0
    Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
  Collecting distro
    Using cached distro-1.8.0-py3-none-any.whl (20 kB)
  Collecting MarkupSafe>=2.0
    Using cached MarkupSafe-2.1.1-cp38-cp38-win_amd64.whl (17 kB)
  Collecting idna<4,>=2.5
    Using cached idna-3.4-py3-none-any.whl (61 kB)
  Collecting charset-normalizer<3,>=2
    Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
  Collecting certifi>=2017.4.17
    Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Installing collected packages: pluginbase, patch-ng, node-semver, ninja, cmake, bottle, wheel, urllib3, six, setuptools, PyYAML, pyparsing, PyJWT, pygments, MarkupSafe, idna, fasteners, distro, colorama, charset-normalizer, certifi, tqdm, requests, python-dateutil, packaging, Jinja2, scikit-build, conan
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  spyder 4.1.4 requires pyqt5<5.13; python_version >= "3", which is not installed.
  spyder 4.1.4 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
  conda 22.9.0 requires ruamel_yaml_conda>=0.11.14, which is not installed.
  gensim 3.8.3 requires Cython==0.29.14, but you have cython 0.29.24 which is incompatible.
  Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 PyJWT-2.6.0 PyYAML-6.0 bottle-0.12.23 certifi-2022.9.24 charset-normalizer-2.1.1 cmake-3.25.0 colorama-0.4.6 conan-1.54.0 distro-1.8.0 fasteners-0.18 idna-3.4 ninja-1.11.1 node-semver-0.6.1 packaging-21.3 patch-ng-1.17.4 pluginbase-1.0.1 pygments-2.13.0 pyparsing-3.0.9 python-dateutil-2.8.2 requests-2.28.1 scikit-build-0.16.2 setuptools-65.6.3 six-1.16.0 tqdm-4.64.1 urllib3-1.26.13 wheel-0.38.4
  Running command Getting requirements to build wheel
  Configuration:
  [settings]
  arch=x86_64
  arch_build=x86_64
  build_type=Release
  compiler=Visual Studio
  compiler.runtime=MD
  compiler.version=16
  os=Windows
  os_build=Windows
  [options]
  [build_requires]
  [env]

  Version ranges solved
      Version range '==5.3' required by 'conanfile.txt' resolved to 'cgal/5.3.2' in local cache
      Version range '>=3.11' required by 'conanfile.txt' resolved to 'nlohmann_json/3.11.2' in local cache

  conanfile.txt: Installing package
  Requirements
      boost/1.75.0 from 'conancenter' - Cache
      bzip2/1.0.8 from 'conancenter' - Cache
      cgal/5.3.2 from 'conancenter' - Cache
      eigen/3.3.9 from 'conancenter' - Cache
      gmp/6.2.1 from 'conancenter' - Cache
      mpfr/4.1.0 from 'conancenter' - Cache
      nlohmann_json/3.11.2 from 'conancenter' - Cache
      zlib/1.2.13 from 'conancenter' - Cache
  Packages
      boost/1.75.0:37050c911e5419517ec6e0761c16c6e262b3e2a3 - Cache
      bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
      cgal/5.3.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      gmp/6.2.1:c1430fa7339501202f6eff5c00c1be2706543a7c - Cache
      mpfr/4.1.0:22b6a90d08e50b15cd1198784b567f3051ae5340 - Cache
      nlohmann_json/3.11.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      zlib/1.2.13:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

  Installing (downloading, building) binaries...
  bzip2/1.0.8: Already installed!
  eigen/3.3.9: Already installed!
  gmp/6.2.1: Already installed!
  nlohmann_json/3.11.2: Already installed!
  zlib/1.2.13: Already installed!
  boost/1.75.0: Already installed!
  boost/1.75.0: Disabled magic autolinking (smart and magic decisions)
  mpfr/4.1.0: Already installed!
  cgal/5.3.2: Already installed!
  conanfile.txt: Generator cmake_find_package created FindCGAL.cmake
  conanfile.txt: Generator cmake_find_package created Findnlohmann_json.cmake
  conanfile.txt: Generator cmake_find_package created FindBoost.cmake
  conanfile.txt: Generator cmake_find_package created FindEigen3.cmake
  conanfile.txt: Generator cmake_find_package created Findmpfr.cmake
  conanfile.txt: Generator cmake_find_package created FindZLIB.cmake
  conanfile.txt: Generator cmake_find_package created FindBZip2.cmake
  conanfile.txt: Generator cmake_find_package created Findgmp.cmake
  conanfile.txt: Generator txt created conanbuildinfo.txt
  conanfile.txt: Aggregating env generators
  conanfile.txt: Generated conaninfo.txt
  conanfile.txt: Generated graphinfo
  running egg_info
  writing python\cgshop2023_pyutils.egg-info\PKG-INFO
  writing dependency_links to python\cgshop2023_pyutils.egg-info\dependency_links.txt
  writing requirements to python\cgshop2023_pyutils.egg-info\requires.txt
  writing top-level names to python\cgshop2023_pyutils.egg-info\top_level.txt
  reading manifest file 'python\cgshop2023_pyutils.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'tests'
  warning: no previously-included files found matching 'apps'
  warning: no files found matching 'CMakeLists.txt' under directory 'src'
  warning: no files found matching '*.h' under directory 'include'
  adding license file 'LICENSE'
  writing manifest file 'python\cgshop2023_pyutils.egg-info\SOURCES.txt'
  Running command Preparing metadata (pyproject.toml)
  Configuration:
  [settings]
  arch=x86_64
  arch_build=x86_64
  build_type=Release
  compiler=Visual Studio
  compiler.runtime=MD
  compiler.version=16
  os=Windows
  os_build=Windows
  [options]
  [build_requires]
  [env]

  Version ranges solved
      Version range '==5.3' required by 'conanfile.txt' resolved to 'cgal/5.3.2' in local cache
      Version range '>=3.11' required by 'conanfile.txt' resolved to 'nlohmann_json/3.11.2' in local cache

  conanfile.txt: Installing package
  Requirements
      boost/1.75.0 from 'conancenter' - Cache
      bzip2/1.0.8 from 'conancenter' - Cache
      cgal/5.3.2 from 'conancenter' - Cache
      eigen/3.3.9 from 'conancenter' - Cache
      gmp/6.2.1 from 'conancenter' - Cache
      mpfr/4.1.0 from 'conancenter' - Cache
      nlohmann_json/3.11.2 from 'conancenter' - Cache
      zlib/1.2.13 from 'conancenter' - Cache
  Packages
      boost/1.75.0:37050c911e5419517ec6e0761c16c6e262b3e2a3 - Cache
      bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
      cgal/5.3.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      gmp/6.2.1:c1430fa7339501202f6eff5c00c1be2706543a7c - Cache
      mpfr/4.1.0:22b6a90d08e50b15cd1198784b567f3051ae5340 - Cache
      nlohmann_json/3.11.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      zlib/1.2.13:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

  Installing (downloading, building) binaries...
  bzip2/1.0.8: Already installed!
  eigen/3.3.9: Already installed!
  gmp/6.2.1: Already installed!
  nlohmann_json/3.11.2: Already installed!
  zlib/1.2.13: Already installed!
  boost/1.75.0: Already installed!
  boost/1.75.0: Disabled magic autolinking (smart and magic decisions)
  mpfr/4.1.0: Already installed!
  cgal/5.3.2: Already installed!
  conanfile.txt: Generator txt created conanbuildinfo.txt
  conanfile.txt: Generator cmake_find_package created FindCGAL.cmake
  conanfile.txt: Generator cmake_find_package created Findnlohmann_json.cmake
  conanfile.txt: Generator cmake_find_package created FindBoost.cmake
  conanfile.txt: Generator cmake_find_package created FindEigen3.cmake
  conanfile.txt: Generator cmake_find_package created Findmpfr.cmake
  conanfile.txt: Generator cmake_find_package created FindZLIB.cmake
  conanfile.txt: Generator cmake_find_package created FindBZip2.cmake
  conanfile.txt: Generator cmake_find_package created Findgmp.cmake
  conanfile.txt: Aggregating env generators
  conanfile.txt: Generated conaninfo.txt
  conanfile.txt: Generated graphinfo
  running dist_info
  creating C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils.egg-info
  writing C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils.egg-info\PKG-INFO
  writing dependency_links to C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils.egg-info\dependency_links.txt
  writing requirements to C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils.egg-info\requires.txt
  writing top-level names to C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils.egg-info\top_level.txt
  writing manifest file 'C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'tests'
  warning: no previously-included files found matching 'apps'
  warning: no files found matching 'CMakeLists.txt' under directory 'src'
  warning: no files found matching '*.h' under directory 'include'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils.egg-info\SOURCES.txt'
  creating 'C:\Users\xxj99\AppData\Local\Temp\pip-modern-metadata-8jz3mpfa\cgshop2023_pyutils-0.2.10.dist-info'
  Running command Building wheel for cgshop2023-pyutils (pyproject.toml)
  Configuration:
  [settings]
  arch=x86_64
  arch_build=x86_64
  build_type=Release
  compiler=Visual Studio
  compiler.runtime=MD
  compiler.version=16
  os=Windows
  os_build=Windows
  [options]
  [build_requires]
  [env]

  Version ranges solved
      Version range '==5.3' required by 'conanfile.txt' resolved to 'cgal/5.3.2' in local cache
      Version range '>=3.11' required by 'conanfile.txt' resolved to 'nlohmann_json/3.11.2' in local cache

  conanfile.txt: Installing package
  Requirements
      boost/1.75.0 from 'conancenter' - Cache
      bzip2/1.0.8 from 'conancenter' - Cache
      cgal/5.3.2 from 'conancenter' - Cache
      eigen/3.3.9 from 'conancenter' - Cache
      gmp/6.2.1 from 'conancenter' - Cache
      mpfr/4.1.0 from 'conancenter' - Cache
      nlohmann_json/3.11.2 from 'conancenter' - Cache
      zlib/1.2.13 from 'conancenter' - Cache
  Packages
      boost/1.75.0:37050c911e5419517ec6e0761c16c6e262b3e2a3 - Cache
      bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
      cgal/5.3.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      gmp/6.2.1:c1430fa7339501202f6eff5c00c1be2706543a7c - Cache
      mpfr/4.1.0:22b6a90d08e50b15cd1198784b567f3051ae5340 - Cache
      nlohmann_json/3.11.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
      zlib/1.2.13:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

  Installing (downloading, building) binaries...
  bzip2/1.0.8: Already installed!
  eigen/3.3.9: Already installed!
  gmp/6.2.1: Already installed!
  nlohmann_json/3.11.2: Already installed!
  zlib/1.2.13: Already installed!
  boost/1.75.0: Already installed!
  boost/1.75.0: Disabled magic autolinking (smart and magic decisions)
  mpfr/4.1.0: Already installed!
  cgal/5.3.2: Already installed!
  conanfile.txt: Generator cmake_find_package created FindCGAL.cmake
  conanfile.txt: Generator cmake_find_package created Findnlohmann_json.cmake
  conanfile.txt: Generator cmake_find_package created FindBoost.cmake
  conanfile.txt: Generator cmake_find_package created FindEigen3.cmake
  conanfile.txt: Generator cmake_find_package created Findmpfr.cmake
  conanfile.txt: Generator cmake_find_package created FindZLIB.cmake
  conanfile.txt: Generator cmake_find_package created FindBZip2.cmake
  conanfile.txt: Generator cmake_find_package created Findgmp.cmake
  conanfile.txt: Generator txt created conanbuildinfo.txt
  conanfile.txt: Aggregating env generators
  conanfile.txt: Generated conaninfo.txt
  conanfile.txt: Generated graphinfo


  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 8.1.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: D:/mingw64/bin/gcc.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 8.1.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: D:/mingw64/bin/c++.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:9 (message):
    MSVC is required to pass this check.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxj99/AppData/Local/Temp/pip-install-yf6jb068/cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "Visual Studio 17 2022 x64 v143" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 17 2022

    could not find any instance of Visual Studio.



  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxj99/AppData/Local/Temp/pip-install-yf6jb068/cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Visual Studio 17 2022 x64 v143" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 16 2019 x64 v142)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is MSVC 19.27.29112.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: D:/Software/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is MSVC 19.27.29112.0
  CMake Warning (dev) at C:/Users/xxj99/AppData/Local/Temp/pip-build-env-uvpqfkzg/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDetermineCXXCompiler.cmake:162 (if):
    Policy CMP0054 is not set: Only interpret if() arguments as variables or
    keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
    details.  Use the cmake_policy command to set the policy and suppress this
    warning.

    Quoted variables like "MSVC" will no longer be dereferenced when the policy
    is set to NEW.  Since the policy is not set the OLD behavior will be used.
  Call Stack (most recent call first):
    CMakeLists.txt:4 (ENABLE_LANGUAGE)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) at C:/Users/xxj99/AppData/Local/Temp/pip-build-env-uvpqfkzg/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDetermineCXXCompiler.cmake:183 (elseif):
    Policy CMP0054 is not set: Only interpret if() arguments as variables or
    keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
    details.  Use the cmake_policy command to set the policy and suppress this
    warning.

    Quoted variables like "MSVC" will no longer be dereferenced when the policy
    is set to NEW.  Since the policy is not set the OLD behavior will be used.
  Call Stack (most recent call first):
    CMakeLists.txt:4 (ENABLE_LANGUAGE)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: D:/Software/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/xxj99/AppData/Local/Temp/pip-install-yf6jb068/cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 16 2019 x64 v142)" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      C:\Users\xxj99\AppData\Local\Temp\pip-install-yf6jb068\cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901\_skbuild\win-amd64-3.8\cmake-build
    Command:
      cmake 'C:\Users\xxj99\AppData\Local\Temp\pip-install-yf6jb068\cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\xxj99\AppData\Local\Temp\pip-install-yf6jb068\cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901\_skbuild\win-amd64-3.8\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.8.3 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\xxj99\AppData\Local\Temp\pip-build-env-uvpqfkzg\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=d:\users\xxj99\anaconda3\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=d:\users\xxj99\anaconda3\Include' '-DPYTHON_LIBRARY:PATH=d:\users\xxj99\anaconda3\libs\python38.lib' '-DPython_EXECUTABLE:PATH=d:\users\xxj99\anaconda3\python.exe' '-DPython_ROOT_DIR:PATH=d:\users\xxj99\anaconda3' '-DPython_INCLUDE_DIR:PATH=d:\users\xxj99\anaconda3\Include' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython3_EXECUTABLE:PATH=d:\users\xxj99\anaconda3\python.exe' '-DPython3_ROOT_DIR:PATH=d:\users\xxj99\anaconda3' '-DPython3_INCLUDE_DIR:PATH=d:\users\xxj99\anaconda3\Include' -DPython3_FIND_REGISTRY:STRING=NEVER '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\xxj99\AppData\Local\Temp\pip-build-env-uvpqfkzg\overlay\Lib\site-packages\ninja\data\bin\ninja' -DCMAKE_BUILD_TYPE:STRING=Release

  -- The CXX compiler identification is MSVC 19.27.29112.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: D:/Software/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Not using CCache
  CMake Warning at cmake/CPM.cmake:62 (message):
    Your project is using an unstable development version of CPM.cmake.  Please
    update to a recent release if possible.  See
    https://github.com/cpm-cmake/CPM.cmake for details.
  Call Stack (most recent call first):
    CMakeLists.txt:20 (include)


  -- CPM: adding package fmt@9.1.0 (9.1.0)
  CMake Error at C:/Users/xxj99/AppData/Local/Temp/pip-build-env-uvpqfkzg/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/ExternalProject.cmake:2790 (message):
    error: could not find git for clone of fmt-populate
  Call Stack (most recent call first):
    C:/Users/xxj99/AppData/Local/Temp/pip-build-env-uvpqfkzg/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/ExternalProject.cmake:4185 (_ep_add_download_command)
    CMakeLists.txt:23 (ExternalProject_Add)


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxj99/AppData/Local/Temp/pip-install-yf6jb068/cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901/_skbuild/win-amd64-3.8/cmake-build/_deps/fmt-subbuild/CMakeFiles/CMakeOutput.log".

  CMake Error at C:/Users/xxj99/AppData/Local/Temp/pip-build-env-uvpqfkzg/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FetchContent.cmake:1604 (message):
    CMake step for fmt failed: 1
  Call Stack (most recent call first):
    C:/Users/xxj99/AppData/Local/Temp/pip-build-env-uvpqfkzg/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FetchContent.cmake:1756:EVAL:2 (__FetchContent_directPopulate)
    C:/Users/xxj99/AppData/Local/Temp/pip-build-env-uvpqfkzg/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FetchContent.cmake:1756 (cmake_language)
    cmake/CPM.cmake:967 (FetchContent_Populate)
    cmake/CPM.cmake:773 (cpm_fetch_package)
    CMakeLists.txt:22 (CPMAddPackage)


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxj99/AppData/Local/Temp/pip-install-yf6jb068/cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "C:\Users\xxj99\AppData\Local\Temp\pip-build-env-uvpqfkzg\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 632, in setup
      env = cmkr.configure(
    File "C:\Users\xxj99\AppData\Local\Temp\pip-build-env-uvpqfkzg\overlay\Lib\site-packages\skbuild\cmaker.py", line 334, in configure
      raise SKBuildError(

  An error occurred while configuring with CMake.
    Command:
      cmake 'C:\Users\xxj99\AppData\Local\Temp\pip-install-yf6jb068\cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\xxj99\AppData\Local\Temp\pip-install-yf6jb068\cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901\_skbuild\win-amd64-3.8\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.8.3 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\xxj99\AppData\Local\Temp\pip-build-env-uvpqfkzg\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=d:\users\xxj99\anaconda3\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=d:\users\xxj99\anaconda3\Include' '-DPYTHON_LIBRARY:PATH=d:\users\xxj99\anaconda3\libs\python38.lib' '-DPython_EXECUTABLE:PATH=d:\users\xxj99\anaconda3\python.exe' '-DPython_ROOT_DIR:PATH=d:\users\xxj99\anaconda3' '-DPython_INCLUDE_DIR:PATH=d:\users\xxj99\anaconda3\Include' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython3_EXECUTABLE:PATH=d:\users\xxj99\anaconda3\python.exe' '-DPython3_ROOT_DIR:PATH=d:\users\xxj99\anaconda3' '-DPython3_INCLUDE_DIR:PATH=d:\users\xxj99\anaconda3\Include' -DPython3_FIND_REGISTRY:STRING=NEVER '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\xxj99\AppData\Local\Temp\pip-build-env-uvpqfkzg\overlay\Lib\site-packages\ninja\data\bin\ninja' -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      C:\Users\xxj99\AppData\Local\Temp\pip-install-yf6jb068\cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901
    Working directory:
      C:\Users\xxj99\AppData\Local\Temp\pip-install-yf6jb068\cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901\_skbuild\win-amd64-3.8\cmake-build
  Please see CMake's output for more information.
  error: subprocess-exited-with-error

  × Building wheel for cgshop2023-pyutils (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'd:\users\xxj99\anaconda3\python.exe' 'd:\users\xxj99\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\xxj99\AppData\Local\Temp\tmp1k2qt3p0'
  cwd: C:\Users\xxj99\AppData\Local\Temp\pip-install-yf6jb068\cgshop2023-pyutils_a15e7b246ce643daa9ea430b67daa901
  ERROR: Failed building wheel for cgshop2023-pyutils
ERROR: Could not build wheels for cgshop2023-pyutils, which is required to install pyproject.toml-based projects
```

**Comment by d-krupke** [comment]
Our assumption right now is that the corresponding system does not have git in its path. It seems like CPM depends on git. We may have to add it as a prerequisite.

**Comment by d-krupke** [comment]
It was indeed git.
