### ISSUE TITLE
Building in docker container not working

### ISSUE THREAD

**Issue by willthbill** [CG-SHOP/pyutils23#26]
Hi. I  have the following setup.
* docker container with archlinux
* CC=gcc
* CXX=g++
* gcc version 12.2.0
* cgal version 5.5.1
* python version 3.10.9
* pip version 22.3.1
* cmake version 3.25.1
* ninja version 1.11.1
* boost version 1.80
* make version 4.4

I have no other programs compiling programs that require cgal using cmake.

I get the following error when I run "pip install cgshop2023-pyutils":
```
Collecting cgshop2023-pyutils
  Downloading cgshop2023_pyutils-0.2.10.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests>=2.25.1
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting chardet>=4.0.0
  Downloading chardet-5.1.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 7.0 MB/s eta 0:00:00
Collecting networkx>=2.5.1
  Downloading networkx-3.0-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 10.2 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Building wheels for collected packages: cgshop2023-pyutils
  Building wheel for cgshop2023-pyutils (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cgshop2023-pyutils (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─
          bzip2/1.0.8:3cfc45772763dad1237052f26c1fe8b2bae3f7d2 - Cache
          cgal/5.3.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          gmp/6.2.1:ad8e75226b300afed4f677889f2042a8be71af50 - Cache
          libbacktrace/cci.20210118:2a19826344ff00be1c04403f2f8e7008ed3a7cc6 - Cache
          mpfr/4.1.0:22d67ced6ca16c91e5bcad03e84f35ef2328258a - Cache
          nlohmann_json/3.11.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          zlib/1.2.13:2a19826344ff00be1c04403f2f8e7008ed3a7cc6 - Cache

      Installing (downloading, building) binaries...
      bzip2/1.0.8: Already installed!
      eigen/3.3.9: Already installed!
      gmp/6.2.1: Already installed!
      libbacktrace/cci.20210118: Already installed!
      nlohmann_json/3.11.2: Already installed!
      zlib/1.2.13: Already installed!
      boost/1.75.0: Already installed!
      mpfr/4.1.0: Already installed!
      cgal/5.3.2: Already installed!
      conanfile.txt: Generator cmake_find_package created FindCGAL.cmake
      conanfile.txt: Generator cmake_find_package created Findnlohmann_json.cmake
      conanfile.txt: Generator cmake_find_package created FindBoost.cmake
      conanfile.txt: Generator cmake_find_package created FindEigen3.cmake
      conanfile.txt: Generator cmake_find_package created Findmpfr.cmake
      conanfile.txt: Generator cmake_find_package created FindZLIB.cmake
      conanfile.txt: Generator cmake_find_package created FindBZip2.cmake
      conanfile.txt: Generator cmake_find_package created Findlibbacktrace.cmake
      conanfile.txt: Generator cmake_find_package created Findgmp.cmake
      conanfile.txt: Generator txt created conanbuildinfo.txt
      conanfile.txt: Aggregating env generators
      conanfile.txt: Generated conaninfo.txt
      conanfile.txt: Generated graphinfo


      --------------------------------------------------------------------------------
      -- Trying "Ninja" g
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-install-fzcoeqlk/cgshop2023-pyutils_70e5cea476fc4a60b9fd1763d62197a3/_skbuild/linux-x86_64-3.10/cmake-build
        Command:
          cmake /tmp/pip-install-fzcoeqlk/cgshop2023-pyutils_70e5cea476fc4a60b9fd1763d62197a3 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-fzcoeqlk/cgshop2023-pyutils_70e5cea476fc4a60b9fd1763d62197a3/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-zisksj31/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/usr/bin/python -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-zisksj31/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

      -- The CXX compiler identification is GNU 12.2.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/g++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Not using CCache
      CMake Warning at cmake/CPM.cmake:62 (message):
        Your project is using an unstable development version of CPM.cmake.  Please
        update to a recent release if possible.  See
        https://github.com/cpm-cmake/CPM.cmake for details.
      Call Stack (most recent call first):
        CMakeLists.txt:20 (include)


      -- CPM: adding package fmt@9.1.0 (9.1.0)
      CMake Error at /tmp/pip-build-env-zisksj31/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/ExternalProject.cmake:2790 (message):
        error: could not find git for clone of fmt-populate
      Call Stack (most
ke_language)
        cmake/CPM.cmake:967 (FetchContent_Populate)
        cmake/CPM.cmake:773 (cpm_fetch_package)
        CMakeLists.txt:22 (CPMAddPackage)


      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-fzcoeqlk/cgshop2023-pyutils_70e5cea476fc4a60b9fd1763d62197a3/_skbuild/linux-x86_64-3.10/cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "/tmp/pip-build-env-zisksj31/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 632, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-zisksj31/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 335, in configure
          raise SKBuildError(

      An error occurred while configuring with CMake.
        Command:
          cmake /tmp/pip-install-fzcoeqlk/cgshop2023-pyutils_70e5cea476fc4a60b9fd1763d62197a3 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-fzcoeqlk/cgshop2023-pyutils_70e5cea476fc4a60b9fd1763d62197a3/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-zisksj31/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/usr/bin/python -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-zisksj31/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-install-fzcoeqlk/cgshop2023-pyutils_70e5cea476fc4a60b9fd1763d62197a3
        Working directory:
          /tmp/pip-install-fzcoeqlk/cgshop2023-pyutils_70e5cea476fc4a60b9fd1763d62197a3/_skbuild/linux-x86_64-3.10/cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cgshop2023-pyutils
Failed to build cgshop2023-pyutils
ERROR: Could not build wheels for cgshop2023-pyutils, which is required to install pyproject.toml-based projects
```

**Comment by phillip-keldenich** [comment]
You don't seem to have git installed in the container. Try if that fixes your issue.

**Comment by willthbill** [comment]
That worked. Thank you

**Comment by phillip-keldenich** [comment]
I'm closing this for now. Since this is the second time someone had an issue missing git in their environment, we might want to try to make the error message a bit better though.
