### ISSUE TITLE
InstanceDataBase only sees instances which have a ".instance.json" extension

### ISSUE THREAD

**Issue by rolfvdhulst** [CG-SHOP/pyutils23#5]
The instanceDataBase only collects instances which are marked with .instance.json and not those with .json. Hence, one cannot verify instances such as maze_001 from the example set, as it will throw an error, whereas the cheese instances work fine.

(Some paths are modified for safety)
```
Traceback (most recent call last):
  File ".../test.py", line 7, in <module>
    instance = idb[solution["instance"]]
  File ".../.local/lib/python3.10/site-packages/cgshop2023_pyutils-0.1.2-py3.10-linux-x86_64.egg/cgshop2023_pyutils/instance_database/instance_database.py", line 61, in __getitem__
    return self._inner_database[name]
  File ".../.local/lib/python3.10/site-packages/cgshop2023_pyutils-0.1.2-py3.10-linux-x86_64.egg/cgshop2023_pyutils/instance_database/instance_file_database.py", line 65, in __getitem__
    path = self._find_path(name)
  File ".../.local/lib/python3.10/site-packages/cgshop2023_pyutils-0.1.2-py3.10-linux-x86_64.egg/cgshop2023_pyutils/instance_database/instance_file_database.py", line 39, in _find_path
    raise KeyError(f"Did not find a suitable file for {name} in {self._path}")
KeyError: 'Did not find a suitable file for maze_001 in .../examples'
```
Perhaps all instances should be marked with .instance.json?

I have been able to run the software and it seems to correctly determine some solutions/triangulations (or atleast, is broken in the same way as my code is).

**Comment by d-krupke** [comment]
Ohh, right. We messed that up in the example instances. The final instances will all fit the naming scheme :)

**Comment by d-krupke** [comment]
As all the instances in the challenge follow this rule and should not result in any problems, I close this issue.
